//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnScreenTranslator.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnScreenTranslator.resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow text selecting.
        /// </summary>
        public static string AllowTextSelecting {
            get {
                return ResourceManager.GetString("AllowTextSelecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key (Optional).
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to apply the new settings?.
        /// </summary>
        public static string ApplyConfirmation {
            get {
                return ResourceManager.GetString("ApplyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Settings.
        /// </summary>
        public static string ApplySettings {
            get {
                return ResourceManager.GetString("ApplySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Rows.
        /// </summary>
        public static string ByRows {
            get {
                return ResourceManager.GetString("ByRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string ConfirmationWindow {
            get {
                return ResourceManager.GetString("ConfirmationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/hide overlay.
        /// </summary>
        public static string CreateDestroyOverlay {
            get {
                return ResourceManager.GetString("CreateDestroyOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Overlay.
        /// </summary>
        public static string CreateOverlay {
            get {
                return ResourceManager.GetString("CreateOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy Overlay.
        /// </summary>
        public static string DestroyOverlay {
            get {
                return ResourceManager.GetString("DestroyOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint URL.
        /// </summary>
        public static string EndpointURL {
            get {
                return ResourceManager.GetString("EndpointURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys:.
        /// </summary>
        public static string HotKeys {
            get {
                return ResourceManager.GetString("HotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Use OnScreenTranslator.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Select the screen area you want to translate using the “Select Area” button or the keyboard shortcut (Alt + Q)..
        /// </summary>
        public static string HowToUseDesc1 {
            get {
                return ResourceManager.GetString("HowToUseDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Create or display the overlay window to show the translation result..
        /// </summary>
        public static string HowToUseDesc2 {
            get {
                return ResourceManager.GetString("HowToUseDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Start the translation process using the corresponding command or hotkey..
        /// </summary>
        public static string HowToUseDesc3 {
            get {
                return ResourceManager.GetString("HowToUseDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. The recognized and translated text will be displayed in a semi-transparent window over the selected screen area..
        /// </summary>
        public static string HowToUseDesc4 {
            get {
                return ResourceManager.GetString("HowToUseDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Language_Arabic {
            get {
                return ResourceManager.GetString("Language_Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Language_Auto {
            get {
                return ResourceManager.GetString("Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (simplified).
        /// </summary>
        public static string Language_Chinese_sim {
            get {
                return ResourceManager.GetString("Language_Chinese_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinise (traditional).
        /// </summary>
        public static string Language_Chinese_tra {
            get {
                return ResourceManager.GetString("Language_Chinese_tra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Language_Czech {
            get {
                return ResourceManager.GetString("Language_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        public static string Language_Danish {
            get {
                return ResourceManager.GetString("Language_Danish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        public static string Language_Dutch {
            get {
                return ResourceManager.GetString("Language_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        public static string Language_Finnish {
            get {
                return ResourceManager.GetString("Language_Finnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Language_German {
            get {
                return ResourceManager.GetString("Language_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        public static string Language_Hindi {
            get {
                return ResourceManager.GetString("Language_Hindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        public static string Language_Indonesian {
            get {
                return ResourceManager.GetString("Language_Indonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string Language_Italian {
            get {
                return ResourceManager.GetString("Language_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Language_Japanese {
            get {
                return ResourceManager.GetString("Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string Language_Korean {
            get {
                return ResourceManager.GetString("Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian.
        /// </summary>
        public static string Language_Persian {
            get {
                return ResourceManager.GetString("Language_Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Language_Polish {
            get {
                return ResourceManager.GetString("Language_Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Language_Portuguese {
            get {
                return ResourceManager.GetString("Language_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Language_Romanian {
            get {
                return ResourceManager.GetString("Language_Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Language_Spanish {
            get {
                return ResourceManager.GetString("Language_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        public static string Language_Thai {
            get {
                return ResourceManager.GetString("Language_Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Language_Turkish {
            get {
                return ResourceManager.GetString("Language_Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Language_Ukrainian {
            get {
                return ResourceManager.GetString("Language_Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Language_Vietnamese {
            get {
                return ResourceManager.GetString("Language_Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language.
        /// </summary>
        public static string LocalizationLabel {
            get {
                return ResourceManager.GetString("LocalizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Overlay.
        /// </summary>
        public static string LockOverlay {
            get {
                return ResourceManager.GetString("LockOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Steps:.
        /// </summary>
        public static string MainSteps {
            get {
                return ResourceManager.GetString("MainSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text translation mode.
        /// </summary>
        public static string OcrMode {
            get {
                return ResourceManager.GetString("OcrMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Only.
        /// </summary>
        public static string OcrOnly {
            get {
                return ResourceManager.GetString("OcrOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time.
        /// </summary>
        public static string OneTime {
            get {
                return ResourceManager.GetString("OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time with waiting new area.
        /// </summary>
        public static string OneTimeWithWaiting {
            get {
                return ResourceManager.GetString("OneTimeWithWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string OverlaySettingsLabel {
            get {
                return ResourceManager.GetString("OverlaySettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin/unpin overlay.
        /// </summary>
        public static string PinUnpinOverlay {
            get {
                return ResourceManager.GetString("PinUnpinOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeatedly.
        /// </summary>
        public static string Repeatedly {
            get {
                return ResourceManager.GetString("Repeatedly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the settings?.
        /// </summary>
        public static string RestoreConfirmation {
            get {
                return ResourceManager.GetString("RestoreConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Settings.
        /// </summary>
        public static string RestoreSettings {
            get {
                return ResourceManager.GetString("RestoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Area To Translate From.
        /// </summary>
        public static string SelectArea {
            get {
                return ResourceManager.GetString("SelectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select area for translation.
        /// </summary>
        public static string SelectAreaOnScreen {
            get {
                return ResourceManager.GetString("SelectAreaOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected theme.
        /// </summary>
        public static string SelectedTheme {
            get {
                return ResourceManager.GetString("SelectedTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Language.
        /// </summary>
        public static string SourceLangLabel {
            get {
                return ResourceManager.GetString("SourceLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/stop translation process.
        /// </summary>
        public static string StartStopTranslation {
            get {
                return ResourceManager.GetString("StartStopTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        public static string TargetLangLabel {
            get {
                return ResourceManager.GetString("TargetLangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more convenient use, you can adjust the translation update interval, overlay transparency, and other settings in the “Settings” menu..
        /// </summary>
        public static string TipDesc {
            get {
                return ResourceManager.GetString("TipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string TranslationSettingsLabel {
            get {
                return ResourceManager.GetString("TranslationSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is off.
        /// </summary>
        public static string TranslationStatusOff {
            get {
                return ResourceManager.GetString("TranslationStatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is on.
        /// </summary>
        public static string TranslationStatusOn {
            get {
                return ResourceManager.GetString("TranslationStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator Engine.
        /// </summary>
        public static string TranslatorEngine {
            get {
                return ResourceManager.GetString("TranslatorEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator Settings.
        /// </summary>
        public static string TranslatorSettings {
            get {
                return ResourceManager.GetString("TranslatorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency (pinned).
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin Overlay.
        /// </summary>
        public static string UnlockOverlay {
            get {
                return ResourceManager.GetString("UnlockOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval (sec).
        /// </summary>
        public static string UpdateInterval {
            get {
                return ResourceManager.GetString("UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mode.
        /// </summary>
        public static string UpdateMode {
            get {
                return ResourceManager.GetString("UpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work mode.
        /// </summary>
        public static string WorkMode {
            get {
                return ResourceManager.GetString("WorkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
